export enum ErrorType {
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  USER_WITH_THIS_EMAIL_ALREADY_EXISTS = "USER_WITH_THIS_EMAIL_ALREADY_EXISTS",
  USER_WITH_THIS_USERNAME_ALREADY_EXISTS = "USER_WITH_THIS_USERNAME_ALREADY_EXISTS",
  USER_WITH_THIS_EMAIL_NOT_FOUND = "USER_WITH_THIS_EMAIL_NOT_FOUND",
}
